version: '3'
services:
  frontend:
    image: 'brainburns/gtd-frontend:0.1.1'
  backend:
    image: 'brainburns/gtd-backend:0.1.2'
    env_file:
      - ~/back_env.list
    # ports:
    #   - "8081:8080"
    # links:
      # - "frontend:frontend"
  nginx:
    image: 'nginx'
    volumes: 
      - "./nginx_config:/etc/nginx"
      - "~/cert:/etc/cert__"
    # links:
      # - "frontend:front"
      # - "backend:back"
    ports:
      - "80:80"